version: '3.7'

services:
 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  platform: linux/amd64
 
 app:
  build: .
  volumes:
  - ./:/app
  depends_on:
      - "mysqldb"

volumes:
  mysql:
  mysql_config: